name: chat_module
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  dio: ^5.4.0
  async_queue: ^2.0.0

  #langchain
  langchain: ^0.4.2
  langchain_openai: ^0.4.1
  langchain_chroma: ^0.1.1
  langchain_google: ^0.2.4
  langchain_mistralai: ^0.0.3
  langchain_ollama: ^0.0.4

  #util
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
